VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsSplitter"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Private src As AcadEntity
Private pt1 As clsPoint
Private pt2 As clsPoint
Private ptRef As clsPoint


Function split(ent As AcadEntity, p1 As clsPoint, p2 As clsPoint, pref As clsPoint)





End Function

